[build]
  command = "npm run build"
  publish = "out"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ."

# Remove the Next.js plugin since we're using static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# For local development only - these are already set in Netlify UI for production
[build.environment]
  NEXT_PUBLIC_API_URL = "https://backend-api-134222868469.us-central1.run.app"

